# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0b3853af2fb6b67fbbaeac5fb16a38e5cf4912595577cd54f95be3cf2a3c1c71055f076a5b0425e98ed36068b3dac61424b683dd9740df3e13845238601213a

test:
  secret_key_base: e46125cd653e0d59a65332950490e14d0d9ab4d27befe1c0537c8bbe4afe0f51c268a31314598d429c2c37077ace08f337cf31eedd25b863560bef736d874206

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
